# Generated by Django 4.2 on 2023-12-26 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isNPC', models.BooleanField(default=False)),
                ('level', models.IntegerField(default=1)),
                ('race', models.CharField(max_length=50)),
                ('image', models.ImageField(default='characters/default.png', upload_to='characters/')),
                ('alignment', models.CharField(choices=[('LEGAL_GOOD', 'Legal Good'), ('LEGAL_NEUTRAL', 'Legal Neutral'), ('LEGAL_EVIL', 'Legal Evil'), ('NEUTRAL_NEUTRAL', 'Neutral Neutral'), ('NEUTRAL_GOOD', 'Neutral Good'), ('NEUTRAL_EVIL', 'Neutral Evil'), ('CHAOTIC_GOOD', 'Chaotic Good'), ('CHAOTIC_NEUTRAL', 'Chaotic Neutral'), ('CHAOTIC_EVIL', 'Chaotic Evil')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loreEntries', to='characters.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='characterClass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='characters.characterclass'),
        ),
    ]
