# Generated by Django 4.2 on 2023-12-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='characterClass',
            field=models.CharField(choices=[('MAGE', 'Mage'), ('EXPLORER', 'Explorer'), ('WARRIOR', 'Warrior'), ('CLERIC', 'Cleric'), ('PALADIN', 'Paladin'), ('BARBARIAN', 'Barbarian'), ('ROGUE', 'Rogue'), ('SORCERER', 'Sorcerer'), ('DRUID', 'Druid'), ('MONK', 'Monk'), ('BARD', 'Bard'), ('WARLOCK', 'Warlock')], max_length=50),
        ),
        migrations.DeleteModel(
            name='CharacterClass',
        ),
    ]
