# Generated by Django 4.2 on 2023-12-26 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_character_habilities_character_statistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='habilities',
        ),
        migrations.RemoveField(
            model_name='character',
            name='statistics',
        ),
        migrations.AddField(
            model_name='habilities',
            name='character',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='character',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character'),
        ),
    ]
