# Generated by Django 5.0 on 2023-12-22 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dragon',
            fields=[
                ('dragon_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('element', models.CharField(choices=[('WATER', 'Water'), ('FIRE', 'Fire'), ('EARTH', 'Earth'), ('WIND', 'Wind'), ('LIGHT', 'Light'), ('DARK', 'Dark')], max_length=10)),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('critical_rate', models.IntegerField()),
                ('critical_damage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id_weapon', models.AutoField(primary_key=True, serialize=False)),
                ('range', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('weapon_type', models.CharField(choices=[('SWORD', 'Sword'), ('BOW', 'Bow'), ('STAFF', 'Staff'), ('AXE', 'Axe'), ('HAMMER', 'Hammer'), ('SPEAR', 'Spear')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Goblin',
            fields=[
                ('id_goblin', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enemies.weapon')),
            ],
        ),
    ]
