# Generated by Django 5.0 on 2023-12-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='critical_rate',
            field=models.FloatField(),
        ),
    ]
