# Generated by Django 5.0 on 2023-12-22 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0002_alter_dragon_critical_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goblin',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Weapon', to='enemies.weapon'),
        ),
    ]
