# Generated by Django 5.0 on 2023-12-22 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemies', '0003_alter_goblin_weapon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goblin',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='goblin',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goblins', to='enemies.weapon'),
        ),
    ]
